// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.1
// source: proto/llm.proto

package llm

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ============ 请求 ============
type ChatRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 多轮对话消息列表
	Messages []*Message `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	// 采样温度,0 表示确定性输出
	Temperature float32 `protobuf:"fixed32,2,opt,name=temperature,proto3" json:"temperature,omitempty"`
	// 最大生成 token 数
	MaxTokens int32 `protobuf:"varint,3,opt,name=max_tokens,json=maxTokens,proto3" json:"max_tokens,omitempty"`
	// 客户端可选传入,用于链路追踪;为空则网关生成
	TraceId       string `protobuf:"bytes,4,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatRequest) Reset() {
	*x = ChatRequest{}
	mi := &file_proto_llm_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatRequest) ProtoMessage() {}

func (x *ChatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_llm_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatRequest.ProtoReflect.Descriptor instead.
func (*ChatRequest) Descriptor() ([]byte, []int) {
	return file_proto_llm_proto_rawDescGZIP(), []int{0}
}

func (x *ChatRequest) GetMessages() []*Message {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *ChatRequest) GetTemperature() float32 {
	if x != nil {
		return x.Temperature
	}
	return 0
}

func (x *ChatRequest) GetMaxTokens() int32 {
	if x != nil {
		return x.MaxTokens
	}
	return 0
}

func (x *ChatRequest) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

type Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          string                 `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"` // system / user / assistant
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_proto_llm_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_proto_llm_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_proto_llm_proto_rawDescGZIP(), []int{1}
}

func (x *Message) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *Message) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

// ============ 非流式响应 ============
type ChatResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Content          string                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`                         // 完整生成内容
	TraceId          string                 `protobuf:"bytes,2,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`          // 回传链路 ID
	InstanceId       string                 `protobuf:"bytes,3,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"` // 实际处理请求的 vLLM 实例,便于排查
	PromptTokens     int32                  `protobuf:"varint,4,opt,name=prompt_tokens,json=promptTokens,proto3" json:"prompt_tokens,omitempty"`
	CompletionTokens int32                  `protobuf:"varint,5,opt,name=completion_tokens,json=completionTokens,proto3" json:"completion_tokens,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ChatResponse) Reset() {
	*x = ChatResponse{}
	mi := &file_proto_llm_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatResponse) ProtoMessage() {}

func (x *ChatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_llm_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatResponse.ProtoReflect.Descriptor instead.
func (*ChatResponse) Descriptor() ([]byte, []int) {
	return file_proto_llm_proto_rawDescGZIP(), []int{2}
}

func (x *ChatResponse) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ChatResponse) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *ChatResponse) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *ChatResponse) GetPromptTokens() int32 {
	if x != nil {
		return x.PromptTokens
	}
	return 0
}

func (x *ChatResponse) GetCompletionTokens() int32 {
	if x != nil {
		return x.CompletionTokens
	}
	return 0
}

// ============ 流式响应(每个 chunk 是一个增量)============
type ChatStreamChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Delta         string                 `protobuf:"bytes,1,opt,name=delta,proto3" json:"delta,omitempty"`        // 本次新增的文本片段(不是全文!)
	Finished      bool                   `protobuf:"varint,2,opt,name=finished,proto3" json:"finished,omitempty"` // 是否结束
	TraceId       string                 `protobuf:"bytes,3,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	InstanceId    string                 `protobuf:"bytes,4,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatStreamChunk) Reset() {
	*x = ChatStreamChunk{}
	mi := &file_proto_llm_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatStreamChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatStreamChunk) ProtoMessage() {}

func (x *ChatStreamChunk) ProtoReflect() protoreflect.Message {
	mi := &file_proto_llm_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatStreamChunk.ProtoReflect.Descriptor instead.
func (*ChatStreamChunk) Descriptor() ([]byte, []int) {
	return file_proto_llm_proto_rawDescGZIP(), []int{3}
}

func (x *ChatStreamChunk) GetDelta() string {
	if x != nil {
		return x.Delta
	}
	return ""
}

func (x *ChatStreamChunk) GetFinished() bool {
	if x != nil {
		return x.Finished
	}
	return false
}

func (x *ChatStreamChunk) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *ChatStreamChunk) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

var File_proto_llm_proto protoreflect.FileDescriptor

const file_proto_llm_proto_rawDesc = "" +
	"\n" +
	"\x0fproto/llm.proto\x12\x03llm\"\x93\x01\n" +
	"\vChatRequest\x12(\n" +
	"\bmessages\x18\x01 \x03(\v2\f.llm.MessageR\bmessages\x12 \n" +
	"\vtemperature\x18\x02 \x01(\x02R\vtemperature\x12\x1d\n" +
	"\n" +
	"max_tokens\x18\x03 \x01(\x05R\tmaxTokens\x12\x19\n" +
	"\btrace_id\x18\x04 \x01(\tR\atraceId\"7\n" +
	"\aMessage\x12\x12\n" +
	"\x04role\x18\x01 \x01(\tR\x04role\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\"\xb6\x01\n" +
	"\fChatResponse\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\x12\x19\n" +
	"\btrace_id\x18\x02 \x01(\tR\atraceId\x12\x1f\n" +
	"\vinstance_id\x18\x03 \x01(\tR\n" +
	"instanceId\x12#\n" +
	"\rprompt_tokens\x18\x04 \x01(\x05R\fpromptTokens\x12+\n" +
	"\x11completion_tokens\x18\x05 \x01(\x05R\x10completionTokens\"\x7f\n" +
	"\x0fChatStreamChunk\x12\x14\n" +
	"\x05delta\x18\x01 \x01(\tR\x05delta\x12\x1a\n" +
	"\bfinished\x18\x02 \x01(\bR\bfinished\x12\x19\n" +
	"\btrace_id\x18\x03 \x01(\tR\atraceId\x12\x1f\n" +
	"\vinstance_id\x18\x04 \x01(\tR\n" +
	"instanceId2q\n" +
	"\n" +
	"LLMGateway\x12+\n" +
	"\x04Chat\x12\x10.llm.ChatRequest\x1a\x11.llm.ChatResponse\x126\n" +
	"\n" +
	"ChatStream\x12\x10.llm.ChatRequest\x1a\x14.llm.ChatStreamChunk0\x01B\x1cZ\x1avllm-gateway/proto/llm;llmb\x06proto3"

var (
	file_proto_llm_proto_rawDescOnce sync.Once
	file_proto_llm_proto_rawDescData []byte
)

func file_proto_llm_proto_rawDescGZIP() []byte {
	file_proto_llm_proto_rawDescOnce.Do(func() {
		file_proto_llm_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_llm_proto_rawDesc), len(file_proto_llm_proto_rawDesc)))
	})
	return file_proto_llm_proto_rawDescData
}

var file_proto_llm_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_llm_proto_goTypes = []any{
	(*ChatRequest)(nil),     // 0: llm.ChatRequest
	(*Message)(nil),         // 1: llm.Message
	(*ChatResponse)(nil),    // 2: llm.ChatResponse
	(*ChatStreamChunk)(nil), // 3: llm.ChatStreamChunk
}
var file_proto_llm_proto_depIdxs = []int32{
	1, // 0: llm.ChatRequest.messages:type_name -> llm.Message
	0, // 1: llm.LLMGateway.Chat:input_type -> llm.ChatRequest
	0, // 2: llm.LLMGateway.ChatStream:input_type -> llm.ChatRequest
	2, // 3: llm.LLMGateway.Chat:output_type -> llm.ChatResponse
	3, // 4: llm.LLMGateway.ChatStream:output_type -> llm.ChatStreamChunk
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_llm_proto_init() }
func file_proto_llm_proto_init() {
	if File_proto_llm_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_llm_proto_rawDesc), len(file_proto_llm_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_llm_proto_goTypes,
		DependencyIndexes: file_proto_llm_proto_depIdxs,
		MessageInfos:      file_proto_llm_proto_msgTypes,
	}.Build()
	File_proto_llm_proto = out.File
	file_proto_llm_proto_goTypes = nil
	file_proto_llm_proto_depIdxs = nil
}
