// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v4.25.1
// source: proto/llm.proto

package llm

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	LLMGateway_Chat_FullMethodName       = "/llm.LLMGateway/Chat"
	LLMGateway_ChatStream_FullMethodName = "/llm.LLMGateway/ChatStream"
)

// LLMGatewayClient is the client API for LLMGateway service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ============ 服务定义 ============
type LLMGatewayClient interface {
	// 一问一答:客户端发请求,等完整结果返回(适合后台批处理、对延迟不敏感场景)
	Chat(ctx context.Context, in *ChatRequest, opts ...grpc.CallOption) (*ChatResponse, error)
	// 流式:服务端持续推送 token 增量(适合前端实时打字机效果)
	// stream 关键字加在返回值上 = server-streaming
	ChatStream(ctx context.Context, in *ChatRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ChatStreamChunk], error)
}

type lLMGatewayClient struct {
	cc grpc.ClientConnInterface
}

func NewLLMGatewayClient(cc grpc.ClientConnInterface) LLMGatewayClient {
	return &lLMGatewayClient{cc}
}

func (c *lLMGatewayClient) Chat(ctx context.Context, in *ChatRequest, opts ...grpc.CallOption) (*ChatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ChatResponse)
	err := c.cc.Invoke(ctx, LLMGateway_Chat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lLMGatewayClient) ChatStream(ctx context.Context, in *ChatRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ChatStreamChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &LLMGateway_ServiceDesc.Streams[0], LLMGateway_ChatStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ChatRequest, ChatStreamChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type LLMGateway_ChatStreamClient = grpc.ServerStreamingClient[ChatStreamChunk]

// LLMGatewayServer is the server API for LLMGateway service.
// All implementations must embed UnimplementedLLMGatewayServer
// for forward compatibility.
//
// ============ 服务定义 ============
type LLMGatewayServer interface {
	// 一问一答:客户端发请求,等完整结果返回(适合后台批处理、对延迟不敏感场景)
	Chat(context.Context, *ChatRequest) (*ChatResponse, error)
	// 流式:服务端持续推送 token 增量(适合前端实时打字机效果)
	// stream 关键字加在返回值上 = server-streaming
	ChatStream(*ChatRequest, grpc.ServerStreamingServer[ChatStreamChunk]) error
	mustEmbedUnimplementedLLMGatewayServer()
}

// UnimplementedLLMGatewayServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLLMGatewayServer struct{}

func (UnimplementedLLMGatewayServer) Chat(context.Context, *ChatRequest) (*ChatResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Chat not implemented")
}
func (UnimplementedLLMGatewayServer) ChatStream(*ChatRequest, grpc.ServerStreamingServer[ChatStreamChunk]) error {
	return status.Error(codes.Unimplemented, "method ChatStream not implemented")
}
func (UnimplementedLLMGatewayServer) mustEmbedUnimplementedLLMGatewayServer() {}
func (UnimplementedLLMGatewayServer) testEmbeddedByValue()                    {}

// UnsafeLLMGatewayServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LLMGatewayServer will
// result in compilation errors.
type UnsafeLLMGatewayServer interface {
	mustEmbedUnimplementedLLMGatewayServer()
}

func RegisterLLMGatewayServer(s grpc.ServiceRegistrar, srv LLMGatewayServer) {
	// If the following call panics, it indicates UnimplementedLLMGatewayServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LLMGateway_ServiceDesc, srv)
}

func _LLMGateway_Chat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LLMGatewayServer).Chat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LLMGateway_Chat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LLMGatewayServer).Chat(ctx, req.(*ChatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LLMGateway_ChatStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ChatRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(LLMGatewayServer).ChatStream(m, &grpc.GenericServerStream[ChatRequest, ChatStreamChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type LLMGateway_ChatStreamServer = grpc.ServerStreamingServer[ChatStreamChunk]

// LLMGateway_ServiceDesc is the grpc.ServiceDesc for LLMGateway service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LLMGateway_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "llm.LLMGateway",
	HandlerType: (*LLMGatewayServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Chat",
			Handler:    _LLMGateway_Chat_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ChatStream",
			Handler:       _LLMGateway_ChatStream_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/llm.proto",
}
